
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;

public class Alta_productos extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    public void fechaIngreso(){
        Calendar ingreso = Calendar.getInstance();
        String dia = Integer.toString(ingreso.get(Calendar.DATE));
        String mes = Integer.toString(ingreso.get(Calendar.MONTH));
        String agno = Integer.toString(ingreso.get(Calendar.YEAR));
        String f_ingreso = agno + "-" + mes + "-" + dia;
        this.jl_timestamp.setText(f_ingreso);
    }
    public void caducidadMetodo(){
        String agno = jcb_agno.getSelectedItem().toString();
        String mes = jcb_mes.getSelectedItem().toString();
        String dia = jcb_dia.getSelectedItem().toString();
        String caducidad = agno + mes + dia;
        this.jl_caducidad.setText(caducidad);        
    }
    public Alta_productos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_tipo = new javax.swing.JLabel();
        jl_timestamp = new javax.swing.JLabel();
        jl_caducidad = new javax.swing.JLabel();
        jl_nombre_p_alta = new javax.swing.JLabel();
        jl_marca_alta = new javax.swing.JLabel();
        jl_contenido_alta = new javax.swing.JLabel();
        jcb_tipo = new javax.swing.JComboBox<>();
        jl_precio_com_alta = new javax.swing.JLabel();
        jl_precio_ven_alta = new javax.swing.JLabel();
        jl_caducidad_alta = new javax.swing.JLabel();
        jl_piguales_altas = new javax.swing.JLabel();
        jtf_nombre_p = new javax.swing.JTextField();
        jtf_precio_com = new javax.swing.JTextField();
        jtf_contenido = new javax.swing.JTextField();
        jtf_precio_ven = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jta_descripcion_alta = new javax.swing.JTextArea();
        jb_insert_alta = new javax.swing.JButton();
        jtf_marca = new javax.swing.JTextField();
        jtf_piguales_alta = new javax.swing.JTextField();
        jl_id_prov_alta = new javax.swing.JLabel();
        jtf_id_prov = new javax.swing.JTextField();
        jcb_agno = new javax.swing.JComboBox<>();
        jcb_mes = new javax.swing.JComboBox<>();
        jcb_dia = new javax.swing.JComboBox<>();
        jb_volver_consul = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        jl_tipo.setText("jLabel1");

        jl_timestamp.setText("jLabel1");

        jl_caducidad.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_nombre_p_alta.setText("Nombre");
        getContentPane().add(jl_nombre_p_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 140, -1, -1));

        jl_marca_alta.setText("Marca");
        getContentPane().add(jl_marca_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 70, -1, -1));

        jl_contenido_alta.setText("Contenido");
        getContentPane().add(jl_contenido_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, -1, -1));

        jcb_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Tipo", "Abarrotes", "Bebidas", "Carnes frías", "Cigarros", "Dulces", "Farmacia", "Frituras", "Lácteos", "Limpieza" }));
        getContentPane().add(jcb_tipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 267, -1));

        jl_precio_com_alta.setText("Precio de compra");
        getContentPane().add(jl_precio_com_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, -1, -1));

        jl_precio_ven_alta.setText("Precio de venta");
        getContentPane().add(jl_precio_ven_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 390, -1, -1));

        jl_caducidad_alta.setText("Caducidad");
        getContentPane().add(jl_caducidad_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, -1, -1));

        jl_piguales_altas.setText("Productos iguales a agregar");
        getContentPane().add(jl_piguales_altas, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, -1, -1));
        getContentPane().add(jtf_nombre_p, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 140, 297, -1));
        getContentPane().add(jtf_precio_com, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 330, 295, -1));

        jtf_contenido.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_contenidoActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_contenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, 297, -1));

        jtf_precio_ven.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_precio_venActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_precio_ven, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 390, 295, -1));

        jta_descripcion_alta.setColumns(20);
        jta_descripcion_alta.setRows(5);
        jScrollPane2.setViewportView(jta_descripcion_alta);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 70, 311, 184));

        jb_insert_alta.setText("Insertar registro");
        jb_insert_alta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_insert_altaMouseClicked(evt);
            }
        });
        getContentPane().add(jb_insert_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 310, -1, -1));
        getContentPane().add(jtf_marca, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 70, 303, -1));
        getContentPane().add(jtf_piguales_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 590, 235, -1));

        jl_id_prov_alta.setText("Proveedor");
        getContentPane().add(jl_id_prov_alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 530, -1, -1));
        getContentPane().add(jtf_id_prov, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 520, 295, -1));

        jcb_agno.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Año", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025" }));
        jcb_agno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcb_agnoActionPerformed(evt);
            }
        });
        getContentPane().add(jcb_agno, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 450, -1, -1));

        jcb_mes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mes", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        getContentPane().add(jcb_mes, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, -1, -1));

        jcb_dia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Día", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        getContentPane().add(jcb_dia, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, -1, -1));

        jb_volver_consul.setText("<----");
        jb_volver_consul.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_volver_consulMouseClicked(evt);
            }
        });
        getContentPane().add(jb_volver_consul, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\81605\\3D Objects\\Sin título.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, -4, 880, 720));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtf_contenidoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_contenidoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_contenidoActionPerformed

    private void jtf_precio_venActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_precio_venActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_precio_venActionPerformed

    private void jb_insert_altaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_insert_altaMouseClicked
        fechaIngreso();
        String tipo = jcb_tipo.getSelectedItem().toString();
        this.jl_tipo.setText(tipo);
        float precio_com=0.0f;
        precio_com = Float.parseFloat(this.jtf_precio_com.getText());
        float precio_ven=0.0f;
        precio_ven = Float.parseFloat(this.jtf_precio_ven.getText());
        jcb_tipo.getSelectedItem().toString();
        caducidadMetodo();
        String proveedor = this.jtf_id_prov.getText();
        String descripcion=this.jta_descripcion_alta.getText();
        String piguales=this.jtf_piguales_alta.getText();
        int piguales1=Integer.parseInt(piguales);
        if(piguales1 >= 1){
            while(piguales1 >= 1){
                conexion mysql = new conexion();
                Connection con = mysql.getConnection();
                PreparedStatement ps = null;
                String sql = ("INSERT INTO PRODUCTOS(NOMBRE_P, MARCA, CONTENIDO, F_INGRESO, TIPO_PROD, PRECIO_COM, PRECIO_VEN, CADUCIDAD, ID_PROV, DESCRIPCION) VALUES (?,?,?,?,?,?,?,?,?,?);");
                try {
                    ps = (PreparedStatement) con.prepareStatement(sql);
                    ps.setString(1, jtf_nombre_p.getText());
                    ps.setString(2, jtf_marca.getText());
                    ps.setString(3, jtf_contenido.getText());
                    ps.setString(4, jl_timestamp.getText());
                    ps.setString(5, jl_tipo.getText());
                    ps.setString(6, jtf_precio_com.getText());
                    ps.setString(7, jtf_precio_ven.getText());
                    ps.setString(8, jl_caducidad.getText());
                    ps.setString(9, jtf_id_prov.getText());
                    ps.setString(10, jta_descripcion_alta.getText());
                    piguales1 = piguales1 - 1;
                    if (jtf_nombre_p.getText().isEmpty() || jtf_marca.getText().isEmpty() || jtf_contenido.getText().isEmpty() || jl_timestamp.getText().isEmpty() || jl_tipo.getText().isEmpty() || jtf_precio_com.getText().isEmpty() || jtf_precio_ven.getText().isEmpty() || jl_caducidad.getText().isEmpty() || jtf_id_prov.getText().isEmpty() || jta_descripcion_alta.getText().isEmpty()){
                        JOptionPane.showMessageDialog(null, "Los campos no deben estar vacíos");
                    }
                    else{
                        ps.executeUpdate();
                        JOptionPane.showMessageDialog(null, "Se insertaron los registros exitosamente");}
                }catch (SQLException err){
                    JOptionPane.showMessageDialog(null, "Error, no se pudo ingresar el registro" + err.getMessage());
                }
            }
        }
    }//GEN-LAST:event_jb_insert_altaMouseClicked

    private void jcb_agnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcb_agnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcb_agnoActionPerformed

    private void jb_volver_consulMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_volver_consulMouseClicked
        Jarc1 Jarc2=new Jarc1();
        Jarc2.setVisible(true);
    }//GEN-LAST:event_jb_volver_consulMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Alta_productos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Alta_productos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JButton jb_insert_alta;
    private javax.swing.JButton jb_volver_consul;
    private javax.swing.JComboBox<String> jcb_agno;
    private javax.swing.JComboBox<String> jcb_dia;
    private javax.swing.JComboBox<String> jcb_mes;
    private javax.swing.JComboBox<String> jcb_tipo;
    private javax.swing.JLabel jl_caducidad;
    private javax.swing.JLabel jl_caducidad_alta;
    private javax.swing.JLabel jl_contenido_alta;
    private javax.swing.JLabel jl_id_prov_alta;
    private javax.swing.JLabel jl_marca_alta;
    private javax.swing.JLabel jl_nombre_p_alta;
    private javax.swing.JLabel jl_piguales_altas;
    private javax.swing.JLabel jl_precio_com_alta;
    private javax.swing.JLabel jl_precio_ven_alta;
    private javax.swing.JLabel jl_timestamp;
    private javax.swing.JLabel jl_tipo;
    private javax.swing.JTextArea jta_descripcion_alta;
    private javax.swing.JTextField jtf_contenido;
    private javax.swing.JTextField jtf_id_prov;
    private javax.swing.JTextField jtf_marca;
    private javax.swing.JTextField jtf_nombre_p;
    private javax.swing.JTextField jtf_piguales_alta;
    private javax.swing.JTextField jtf_precio_com;
    private javax.swing.JTextField jtf_precio_ven;
    // End of variables declaration//GEN-END:variables
}
