
import java.awt.Component;


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author Adriàn
 */

public class Jarc1 extends javax.swing.JFrame {
    private Connection conexion;
    private Statement st;
    private ResultSet rs;
    
    
    
    /**
     * Creates new form Jarc
     */

    public Jarc1() {
        initComponents();
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jl_logo_jarc = new javax.swing.JLabel();
        jl_encargado_jarc = new javax.swing.JLabel();
        jl_encargado1_jarc = new javax.swing.JLabel();
        jl_recibido_jarc = new javax.swing.JLabel();
        jl_cambio_jarc = new javax.swing.JLabel();
        jl_cambio1_jarc = new javax.swing.JLabel();
        jl_total_jarc = new javax.swing.JLabel();
        jl_total1_jarc = new javax.swing.JLabel();
        jtf_recibido1 = new javax.swing.JTextField();
        jc_fechadehoy_p_jarc = new com.toedter.calendar.JCalendar();
        jb_altas = new javax.swing.JButton();
        jb_consultas = new javax.swing.JButton();
        jb_ventas = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jl_imagen_jarc = new javax.swing.JLabel();
        jtf_nombre_p_jarc = new javax.swing.JTextField();
        jl_nombre_p_jarc = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jl_precio_jarc = new javax.swing.JLabel();
        jl_precio2_p_jarc = new javax.swing.JLabel();
        jb_aceptar_jarc = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jt_ventas = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_logo_jarc.setIcon(new javax.swing.ImageIcon("C:\\Users\\81605\\Documents\\Tercer cuatrimestre\\Integradora\\logo_Los Arcos.PNG")); // NOI18N
        getContentPane().add(jl_logo_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 13, -1, 142));

        jl_encargado_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_encargado_jarc.setText("Vendedor");
        getContentPane().add(jl_encargado_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 920, 88, -1));

        jl_encargado1_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(jl_encargado1_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 920, 201, 35));

        jl_recibido_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_recibido_jarc.setText("Recibido");
        getContentPane().add(jl_recibido_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 930, 75, 35));

        jl_cambio_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_cambio_jarc.setText("Cambio");
        getContentPane().add(jl_cambio_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 930, 68, -1));

        jl_cambio1_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_cambio1_jarc.setText("$$$$$$");
        getContentPane().add(jl_cambio1_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 930, 77, -1));

        jl_total_jarc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_total_jarc.setText("Total");
        getContentPane().add(jl_total_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 930, 69, -1));

        jl_total1_jarc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_total1_jarc.setText("$$$$$$");
        getContentPane().add(jl_total1_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1340, 930, 90, -1));

        jtf_recibido1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtf_recibido1ActionPerformed(evt);
            }
        });
        getContentPane().add(jtf_recibido1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 930, 179, -1));
        getContentPane().add(jc_fechadehoy_p_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(1120, 20, 320, -1));

        jb_altas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jb_altas.setText("Alta de productos");
        jb_altas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_altasMouseClicked(evt);
            }
        });
        getContentPane().add(jb_altas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 330, 320, 60));

        jb_consultas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jb_consultas.setText("Consultas");
        jb_consultas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_consultasMouseClicked(evt);
            }
        });
        jb_consultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jb_consultasActionPerformed(evt);
            }
        });
        getContentPane().add(jb_consultas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, 320, 60));

        jb_ventas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jb_ventas.setText("Ventas");
        getContentPane().add(jb_ventas, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 190, 320, 50));

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_imagen_jarc.setBorder(javax.swing.BorderFactory.createTitledBorder("Imagen"));
        jPanel1.add(jl_imagen_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 24, 184, 193));

        jtf_nombre_p_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jPanel1.add(jtf_nombre_p_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 50, 536, -1));

        jl_nombre_p_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jl_nombre_p_jarc.setText("Nombre del producto");
        jPanel1.add(jl_nombre_p_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 50, -1, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Cantidad");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 130, 210, -1));

        jl_precio_jarc.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jl_precio_jarc.setText("Precio");
        jPanel1.add(jl_precio_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 85, 32));

        jl_precio2_p_jarc.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jl_precio2_p_jarc.setText("$$$$$$");
        jPanel1.add(jl_precio2_p_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, -1, -1));

        jb_aceptar_jarc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jb_aceptar_jarc.setText("Siguiente producto");
        jb_aceptar_jarc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jb_aceptar_jarcMouseClicked(evt);
            }
        });
        jPanel1.add(jb_aceptar_jarc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 180, 200, 44));

        jt_ventas.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        jt_ventas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jt_ventas);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1, 250, 1080, 450));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jb_altasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_altasMouseClicked
        Alta_productos alta=new Alta_productos();
          alta.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jb_altasMouseClicked

    private void jb_consultasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_consultasMouseClicked
        Consultas2 verjarc = new Consultas2();
        verjarc.setVisible(true);
    }//GEN-LAST:event_jb_consultasMouseClicked

    private void jb_consultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jb_consultasActionPerformed
       
    }//GEN-LAST:event_jb_consultasActionPerformed

    private void jtf_recibido1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtf_recibido1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtf_recibido1ActionPerformed

    private void jb_aceptar_jarcMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jb_aceptar_jarcMouseClicked

    }//GEN-LAST:event_jb_aceptar_jarcMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Jarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Jarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Jarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Jarc.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Jarc().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton jb_aceptar_jarc;
    private javax.swing.JButton jb_altas;
    private javax.swing.JButton jb_consultas;
    private javax.swing.JButton jb_ventas;
    private com.toedter.calendar.JCalendar jc_fechadehoy_p_jarc;
    private javax.swing.JLabel jl_cambio1_jarc;
    private javax.swing.JLabel jl_cambio_jarc;
    private javax.swing.JLabel jl_encargado1_jarc;
    private javax.swing.JLabel jl_encargado_jarc;
    private javax.swing.JLabel jl_imagen_jarc;
    private javax.swing.JLabel jl_logo_jarc;
    private javax.swing.JLabel jl_nombre_p_jarc;
    private javax.swing.JLabel jl_precio2_p_jarc;
    private javax.swing.JLabel jl_precio_jarc;
    private javax.swing.JLabel jl_recibido_jarc;
    private javax.swing.JLabel jl_total1_jarc;
    private javax.swing.JLabel jl_total_jarc;
    private javax.swing.JTable jt_ventas;
    private javax.swing.JTextField jtf_nombre_p_jarc;
    private javax.swing.JTextField jtf_recibido1;
    // End of variables declaration//GEN-END:variables
}
